apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 80
    protocol: TCP
    name: nginx
  - port: 9002
    targetPort: 1180
    protocol: TCP
    name: multitool
  selector:
    app: my-app
